current_tool: imgedit
duration: 1.0
img2video:
  input_image_path: /Users/classfoo/ai/filmeto/workspace/demo/timeline/1/image.png
  logs: ✅ 执行完成
  model: comfy_ui
  percent: 100
  prompt: 小猫抬起强瞄准镜头，发射火枪
  timeline_index: 1
  tool: img2video
layers:
- height: 1280
  id: 1
  locked: false
  name: Layer-1
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1360
  id: 2
  locked: false
  name: Layer-2
  type: image
  visible: true
  width: 768
  x: 0
  y: 0
- height: 1280
  id: 3
  locked: false
  name: Layer-3
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 4
  locked: false
  name: Layer-4
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 5
  locked: false
  name: Layer-5
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 6
  locked: false
  name: Layer-6
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 7
  locked: false
  name: Layer-7
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 8
  locked: false
  name: Layer-8
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 9
  locked: false
  name: Layer-9
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 10
  locked: false
  name: Layer-10
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 11
  locked: false
  name: Layer-11
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 12
  locked: false
  name: Layer-12
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
text2img:
  image_resource_name: 80cbc168-585f-4685-979a-d21b7ea0bb95_ComfyUI_01184_.png
  image_resource_path: resources/images/80cbc168-585f-4685-979a-d21b7ea0bb95_ComfyUI_01184_.png
  logs: Task completed
  model: comfy_ui
  percent: 95
  prompt: 真实风格，一只小猫穿着靴子，带着帽子，腰间别着一把火枪，站在城门口
  reference_image_path: null
  resources:
  - resource_id: 752c0e78-c4f9-4287-a290-2ec22afdac7c
    resource_name: 80cbc168-585f-4685-979a-d21b7ea0bb95_ComfyUI_01184_.png
    resource_path: resources/images/80cbc168-585f-4685-979a-d21b7ea0bb95_ComfyUI_01184_.png
    type: image
  status: success
  timeline_index: 1
  tool: text2img
