current_tool: imgedit
duration: 1.0
img2video:
  input_image_path: /Users/classfoo/ai/filmeto/workspace/demo/timeline/1/image.png
  logs: ✅ 执行完成
  model: comfy_ui
  percent: 100
  prompt: 小猫抬起强瞄准镜头，发射火枪
  timeline_index: 1
  tool: img2video
layers:
- height: 1280
  id: 1
  locked: false
  name: Layer-1
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 2
  locked: false
  name: Layer-2
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 3
  locked: false
  name: Layer-3
  type: video
  visible: true
  width: 720
  x: 0
  y: 0
- height: 1280
  id: 4
  locked: false
  name: Layer-4
  type: image
  visible: true
  width: 720
  x: 0
  y: 0
text2img:
  logs: ✅ 执行完成
  model: comfy_ui
  percent: 100
  prompt: 真实风格，一只小猫穿着靴子，带着帽子，腰间别着一把火枪，站在城门口
  timeline_index: 1
  tool: text2img
